baseURL = "http://nixos.tokyo/about/"
languageCode = "ja"
title = "nixos.tokyo"
theme = "hugo-elate-theme"

[params]
  staticDir = "static"

  # Meta
  author = "hyphon81"
  description = "The NixOS Fan Site in Tokyo Japan."
  email = "zero812n@gmail.com"
  # Navigation
  [params.navigation]
    brand = "nixos.tokyo"
    home = "Home"
    #work = "NixOSについて"
    testimonials = "Testimonials"
    services = "NixOSについて"
    about = "その他"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[menu.prepend]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "The NixOS Fan Site in Tokyo Japan"
    subtitle = '<img src="logo/nixos-logo-only-hires.png" alt="NixOSのロゴ" width="350" height="300"><br>ここは<b>NixOS</b>のファンサイトです。'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "NixOSとは？"
    description = """
      Linuxのディストロの1つです。
      純粋関数型パッケージマネージャである
      \"Nix\"を基礎として動作します。
    """
    url = "#fh5co-services"
    nav = "work"
    button = "特徴"
    icon = "icon-question"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "使い方など"
    description = """
    1つの設定ファイルの変更で、
    すべての設定が可能です。
    設定の仕方についての説明は以下から。
    """
    url = "https://nixos.tokyo/knowledge/"
    button = "設定の仕方"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "ブログ"
    description = """
    個人的なブログです。
    NixOSやそれに関わることを書いていこうと思っています。
    """
    url = "https://nixos.tokyo/blog/"
    button = "読んでみる"
    icon = "icon-note"
    img = "img_10.jpg"

  # Work section
  [params.work]
    enable = false

  # Testimonials section
  [params.testimonials]
    enable = false

  # Services section
  [params.services]
    enable = true
    title = "NixOSについて"
    description = "NixOSは以下の特徴を持ったOSです。"

    [[params.services.item]]
      title = "純粋関数型"
      description = "パッケージマネージャやOS自体も純粋関数型の考え方を取り入れています。"
      icon = "icon-none"
      text = "&lambda;"

    [[params.services.item]]
      title = "Linux"
      description = "NixOSはNixパッケージマネージャを利用したLinuxディストリビューションです。"
      icon = "icon-linux"
      text = ""

    [[params.services.item]]
      title = "デプロイ向き"
      description = "NixOpsツールでNixOSをQEMU、VirtualBoxやAmazon EC2に展開できます。"
      icon = "icon-monitor"
      text = ""

      [[params.services.item]]
      title = "宣言型設定"
      description = "一つの設定ファイルでシステムをカスタマイズできます。"      
      icon = "icon-gear"
      text = ""

  # About section
  [params.about]
    enable = true
    title = "その他の情報"
    description = ""

    [[params.about.item]]
      name = "nixos.org"
      position = "NixOSの公式ホームページ"
      description = "<a href=\"https://nixos.org/\">https://nixos.org/</a>"
      img = "nix-wiki.png"
      alt = "Nixロゴ"
      social = [
        ["icon-twitter", "https://twitter.com/nixos_org"]
      ]

    [[params.about.item]]
      name = "Tokyo NixOS Meetup"
      position = "NixOSに関する集まり"
      description = "Ericさん主催のMeetupです。"
      img = "logo--mSwarm.svg"
      alt = "Meetupロゴ"
      meetup = true

    [[params.about.item]]
      name = "hyphon81"
      position = "このサイトの管理人"
      description = "NixOSでOpenStackを構築するコードを書いてみました。<a href=\"https://github.com/hyphon81/Nixtack\">Nixtack</a>"
      img = "kani003_95.png"
      alt = "アイコン"
      social = [
        ["icon-twitter", "https://twitter.com/yonekawa_masa"],
        ["icon-facebook", "https://www.facebook.com/masa.yonekawa"],
        ["icon-github", "https://github.com/hyphon81"],
        ["icon-linkedin", "https://www.linkedin.com/in/masayonekawa/"]
      ]

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = false
    map = false

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
